string =input('enter danbooru tags: ')
result = string.replace("absurdres ","")
result = result.replace("highres ","")
result = result.replace("watermark ","")
result = result.replace("commentary ","")
result = result.replace("commentary request ","")
result = result.replace("translated ","")
speech = input("Delete Speech bubbles? (y/n): ")
if speech == "y":
    result.replace("speech bubble ","")
result = result.replace(" ",", ").replace("_"," ").replace("(","\(").replace(")","\)")
print(" ")
print(result+", masterpiece, best quality, good quality")